# Generated by Django 5.1.3 on 2025-02-06 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohere_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompthistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cohere_app.usernames'),
        ),
    ]
